name: validacion

on:
  push:
    branches:
      - master

jobs:
  validacion_clave:
    name: validacion_clave
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Validar mensaje de commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *'ROMA'* ]]; then
            git checkout -b polar
            git push -u origin polar
          else
            echo "El mensaje del commit no contiene 'ROMA'. No se realizará ninguna acción."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
