name: validación
on:
  push:
    branches: [master]

jobs:
  validacion_clave:
    name: validacion_clave
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verificar repositorio de Git
        run: git status
        
      - name: Validar mensaje de commit
        if: ${{ contains(github.event.head_commit.message, 'ROMA') }}
        run: |        
          
          git push -f -u origin polar
        
    
          
      
          
              
