on:
     push:
         branches:
              [master]
jobs:
  validacion_clave:
    name: validacion_clave
    runs-on: ubuntu-latest

    steps:
      -  if: ${{ contains(github.event.head_commit.message, 'ROMA') }}
      -  name: Crear rama
         run: |
           git checkout -b polar
           git push -f -u origin polar
      
          
              
