name: validación
on:
  push:
    branches:
      - master

jobs:
  validacion_clave:
    name: validacion_clave
    runs-on: ubuntu-latest

    steps:
      - name: Validar mensaje de commit
        run: |
          if: ${{ contains(github.event.head_commit.message, 'ROMA') }}; then
            # El mensaje del commit contiene 'ROMA'.
            git checkout -b polar
            git push -f -u origin polar
          else
            # El mensaje del commit no contiene 'ROMA'.
            echo "No se realizará ninguna acción."
          fi

      
          
              
